/**
 * Auto-generated type declarations for TypeInfo.
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on next generation.
 * 
 * Generated: 2025-11-20T22:50:27.099Z
 * Generated by: mint-tsdocs
 * 
 * This file provides VSCode autocomplete for TypeInfo imports.
 * @version 1.0.0
 */

/**
 * TypeTree property structure
 */
export interface TypeTreeProperty {
  name: string;
  type: string;
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  defaultValue?: string;
  properties?: TypeTreeProperty[];
}

/**
 * Type information organized by package and API item.
 * Provides full autocomplete for all documented types.
 */
export const TypeInfo: {
  "MintTsdocs": {
    "ApiExtractorApiReportConfig": TypeTreeProperty;
    "ApiExtractorCompilerConfig": TypeTreeProperty;
    "ApiExtractorConfig": TypeTreeProperty;
    "ApiExtractorDocModelConfig": TypeTreeProperty;
    "ApiExtractorDtsRollupConfig": TypeTreeProperty;
    "ApiExtractorMessagesConfig": TypeTreeProperty;
    "ApiModelError": TypeTreeProperty;
    "ApiResolutionCache": TypeTreeProperty;
    "ApiResolutionCacheOptions": TypeTreeProperty;
    "ApiSurfaceStats": TypeTreeProperty;
    "CacheManager": TypeTreeProperty;
    "CacheManagerOptions": TypeTreeProperty;
    "CustomDocNodes": TypeTreeProperty;
    "CustomMarkdownEmitter": TypeTreeProperty;
    "DebugFunction": TypeTreeProperty;
    "Debugger": TypeTreeProperty;
    "DebugLevel": TypeTreeProperty;
    "DocEmphasisSpan": TypeTreeProperty;
    "DocExpandable": TypeTreeProperty;
    "DocHeading": TypeTreeProperty;
    "DocNoteBox": TypeTreeProperty;
    "DocTable": TypeTreeProperty;
    "DocTableCell": TypeTreeProperty;
    "DocTableRow": TypeTreeProperty;
    "DocumentationCoverageStats": TypeTreeProperty;
    "DocumentationError": TypeTreeProperty;
    "DocumentationHelper": TypeTreeProperty;
    "DocumentationStatistics": TypeTreeProperty;
    "DocumentationStats": TypeTreeProperty;
    "ErrorBoundary": TypeTreeProperty;
    "ErrorBoundaryOptions": TypeTreeProperty;
    "ErrorContext": TypeTreeProperty;
    "ErrorResult": TypeTreeProperty;
    "FileSystemError": TypeTreeProperty;
    "GeneratedFilesStats": TypeTreeProperty;
    "GlobalErrorBoundary": TypeTreeProperty;
    "ICustomMarkdownEmitterOptions": TypeTreeProperty;
    "IDocEmphasisSpanParameters": TypeTreeProperty;
    "IDocHeadingParameters": TypeTreeProperty;
    "IDocNoteBoxParameters": TypeTreeProperty;
    "IDocTableCellParameters": TypeTreeProperty;
    "IDocTableParameters": TypeTreeProperty;
    "IDocTableRowParameters": TypeTreeProperty;
    "IMarkdownDocumenterOptions": TypeTreeProperty;
    "IMarkdownEmitterContext": TypeTreeProperty;
    "IMarkdownEmitterOptions": TypeTreeProperty;
    "IndentedWriter": TypeTreeProperty;
    "IReturnData": TypeTreeProperty;
    "ITableData": TypeTreeProperty;
    "ITableRow": TypeTreeProperty;
    "ITemplateData": TypeTreeProperty;
    "ITemplateEngineOptions": TypeTreeProperty;
    "ITemplateManagerOptions": TypeTreeProperty;
    "LiquidTemplateEngine": TypeTreeProperty;
    "LiquidTemplateManager": TypeTreeProperty;
    "MarkdownDocumenter": TypeTreeProperty;
    "MarkdownEmitter": TypeTreeProperty;
    "MessageReportingItem": TypeTreeProperty;
    "MintlifyTsDocsConfig": TypeTreeProperty;
    "NavigationItem": TypeTreeProperty;
    "NavigationManager": TypeTreeProperty;
    "NavigationManagerOptions": TypeTreeProperty;
    "ObjectTypeAnalyzer": TypeTreeProperty;
    "ResolvedConfig": TypeTreeProperty;
    "ResolvedTemplateConfig": TypeTreeProperty;
    "SecurityError": TypeTreeProperty;
    "SecurityUtils": TypeTreeProperty;
    "TemplateConfig": TypeTreeProperty;
    "TemplateDataConverter": TypeTreeProperty;
    "TemplateEngine": TypeTreeProperty;
    "TemplateManager": TypeTreeProperty;
    "TypeAnalysisCache": TypeTreeProperty;
    "TypeAnalysisCacheOptions": TypeTreeProperty;
    "TypeCoverageStats": TypeTreeProperty;
    "TypeInfoGenerator": TypeTreeProperty;
    "TypeTreeGroupProps": TypeTreeProperty;
    "TypeTreeProperty": TypeTreeProperty;
    "TypeTreeProps": TypeTreeProperty;
    "Utilities": TypeTreeProperty;
    "ValidationError": TypeTreeProperty;
  };
};
