/**
 * Auto-generated type information for TypeTree components.
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on next generation.
 * 
 * Generated: 2025-11-20T03:57:47.866Z
 * Generated by: mint-tsdocs
 * 
 * @version 1.0.0
 */

/**
 * Type information organized by package and API item.
 * Use this to get TypeTreeProperty-compatible data for any documented type.
 * 
 * @example
 * ```jsx
 * import { TypeInfo } from "/snippets/tsdocs/TypeInfo.jsx"
 * 
 * <TypeTree {...TypeInfo.MyPackage.MyInterface} />
 * 
 * // Or access nested properties:
 * const apiModelProp = TypeInfo.MintTsdocs.IMarkdownDocumenterOptions.properties.find(
 *   p => p.name === "apiModel"
 * );
 * ```
 */
export const TypeInfo = {
  "MintTsdocs": {
    "ApiExtractorApiReportConfig": {
      "name": "ApiExtractorApiReportConfig",
      "type": "interface",
      "properties": [
        {
          "name": "enabled",
          "type": "boolean",
          "required": false
        },
        {
          "name": "reportFileName",
          "type": "string",
          "required": false
        },
        {
          "name": "reportFolder",
          "type": "string",
          "required": false
        },
        {
          "name": "reportTempFolder",
          "type": "string",
          "required": false
        }
      ]
    },
    "ApiExtractorCompilerConfig": {
      "name": "ApiExtractorCompilerConfig",
      "type": "interface",
      "description": "Unified configuration types for mint-tsdocs",
      "properties": [
        {
          "name": "skipLibCheck",
          "type": "boolean",
          "required": false
        },
        {
          "name": "tsconfigFilePath",
          "type": "string",
          "required": false
        }
      ]
    },
    "ApiExtractorConfig": {
      "name": "ApiExtractorConfig",
      "type": "interface",
      "properties": [
        {
          "name": "apiReport",
          "type": "ApiExtractorApiReportConfig",
          "description": "API report (.api.md) generation settings",
          "required": false
        },
        {
          "name": "bundledPackages",
          "type": "string[]",
          "description": "NPM packages to treat as part of this package",
          "required": false
        },
        {
          "name": "compiler",
          "type": "ApiExtractorCompilerConfig",
          "description": "TypeScript compiler options",
          "required": false
        },
        {
          "name": "configPath",
          "type": "string",
          "description": "Path to custom api-extractor.json file. If specified, will use this instead of generating one.",
          "required": false
        },
        {
          "name": "docModel",
          "type": "ApiExtractorDocModelConfig",
          "description": "Doc model (.api.json) generation settings",
          "required": false
        },
        {
          "name": "dtsRollup",
          "type": "ApiExtractorDtsRollupConfig",
          "description": "TypeScript declaration rollup settings",
          "required": false
        },
        {
          "name": "messages",
          "type": "ApiExtractorMessagesConfig",
          "description": "Message reporting configuration",
          "required": false
        }
      ]
    },
    "ApiExtractorDocModelConfig": {
      "name": "ApiExtractorDocModelConfig",
      "type": "interface",
      "properties": [
        {
          "name": "enabled",
          "type": "boolean",
          "required": false
        },
        {
          "name": "projectFolderUrl",
          "type": "string",
          "required": false
        }
      ]
    },
    "ApiExtractorDtsRollupConfig": {
      "name": "ApiExtractorDtsRollupConfig",
      "type": "interface",
      "properties": [
        {
          "name": "alphaTrimmedFilePath",
          "type": "string",
          "required": false
        },
        {
          "name": "betaTrimmedFilePath",
          "type": "string",
          "required": false
        },
        {
          "name": "enabled",
          "type": "boolean",
          "required": false
        },
        {
          "name": "publicTrimmedFilePath",
          "type": "string",
          "required": false
        },
        {
          "name": "untrimmedFilePath",
          "type": "string",
          "required": false
        }
      ]
    },
    "ApiExtractorMessagesConfig": {
      "name": "ApiExtractorMessagesConfig",
      "type": "interface",
      "properties": [
        {
          "name": "compilerMessageReporting",
          "type": "Record<string, MessageReportingItem>",
          "required": false
        },
        {
          "name": "extractorMessageReporting",
          "type": "Record<string, MessageReportingItem>",
          "required": false
        },
        {
          "name": "tsdocMessageReporting",
          "type": "Record<string, MessageReportingItem>",
          "required": false
        }
      ]
    },
    "ApiModelError": {
      "name": "ApiModelError",
      "type": "class",
      "description": "API model-related errors"
    },
    "ApiResolutionCache": {
      "name": "ApiResolutionCache",
      "type": "class",
      "description": "Simple LRU cache for API resolution results"
    },
    "ApiResolutionCacheOptions": {
      "name": "ApiResolutionCacheOptions",
      "type": "interface",
      "description": "Configuration options for API resolution cache",
      "properties": [
        {
          "name": "enabled",
          "type": "boolean",
          "description": "Whether to enable caching",
          "required": false
        },
        {
          "name": "maxSize",
          "type": "number",
          "description": "Maximum number of cached resolutions",
          "required": false
        }
      ]
    },
    "ApiSurfaceStats": {
      "name": "ApiSurfaceStats",
      "type": "interface",
      "description": "Statistics about the API surface area with per-type coverage",
      "properties": [
        {
          "name": "classes",
          "type": "TypeCoverageStats",
          "required": true
        },
        {
          "name": "enums",
          "type": "TypeCoverageStats",
          "required": true
        },
        {
          "name": "functions",
          "type": "TypeCoverageStats",
          "required": true
        },
        {
          "name": "interfaces",
          "type": "TypeCoverageStats",
          "required": true
        },
        {
          "name": "methods",
          "type": "TypeCoverageStats",
          "required": true
        },
        {
          "name": "namespaces",
          "type": "TypeCoverageStats",
          "required": true
        },
        {
          "name": "properties",
          "type": "TypeCoverageStats",
          "required": true
        },
        {
          "name": "typeAliases",
          "type": "TypeCoverageStats",
          "required": true
        },
        {
          "name": "variables",
          "type": "TypeCoverageStats",
          "required": true
        }
      ]
    },
    "CacheManager": {
      "name": "CacheManager",
      "type": "class",
      "description": "Centralized cache manager for coordinating all caching operations",
      "properties": [
        {
          "name": "apiResolution",
          "type": "ApiResolutionCache",
          "description": "Get the API resolution cache",
          "required": true
        },
        {
          "name": "typeAnalysis",
          "type": "TypeAnalysisCache",
          "description": "Get the type analysis cache",
          "required": true
        }
      ]
    },
    "CacheManagerOptions": {
      "name": "CacheManagerOptions",
      "type": "interface",
      "description": "Configuration for all cache types",
      "properties": [
        {
          "name": "apiResolution",
          "type": "ApiResolutionCacheOptions",
          "description": "API resolution cache options",
          "required": false
        },
        {
          "name": "enabled",
          "type": "boolean",
          "description": "Enable caching globally",
          "required": false
        },
        {
          "name": "enableStats",
          "type": "boolean",
          "description": "Enable cache statistics reporting",
          "required": false
        },
        {
          "name": "typeAnalysis",
          "type": "TypeAnalysisCacheOptions",
          "description": "Type analysis cache options",
          "required": false
        }
      ]
    },
    "CustomDocNodes": {
      "name": "CustomDocNodes",
      "type": "class",
      "properties": [
        {
          "name": "configuration",
          "type": "TSDocConfiguration",
          "required": true
        }
      ]
    },
    "CustomMarkdownEmitter": {
      "name": "CustomMarkdownEmitter",
      "type": "class",
      "description": "Custom markdown emitter that extends the base MarkdownEmitter to provide Mintlify-specific formatting and cross-reference resolution."
    },
    "DebugFunction": {
      "name": "DebugFunction",
      "type": "type",
      "description": "Debug function type (matches debug package signature)"
    },
    "Debugger": {
      "name": "Debugger",
      "type": "interface",
      "description": "Debugger instance with level-specific methods",
      "properties": [
        {
          "name": "debug",
          "type": "DebugFunction",
          "description": "Log debug-level messages",
          "required": true
        },
        {
          "name": "error",
          "type": "DebugFunction",
          "description": "Log error-level messages (always shown when debugging enabled)",
          "required": true
        },
        {
          "name": "info",
          "type": "DebugFunction",
          "description": "Log info-level messages",
          "required": true
        },
        {
          "name": "namespace",
          "type": "string",
          "description": "Get the namespace for this debugger",
          "required": true
        },
        {
          "name": "trace",
          "type": "DebugFunction",
          "description": "Log trace-level messages (most verbose)",
          "required": true
        },
        {
          "name": "warn",
          "type": "DebugFunction",
          "description": "Log warning-level messages",
          "required": true
        }
      ]
    },
    "DebugLevel": {
      "name": "DebugLevel",
      "type": "type"
    },
    "DocEmphasisSpan": {
      "name": "DocEmphasisSpan",
      "type": "class",
      "description": "Represents a span of text that is styled with CommonMark emphasis (italics), strong emphasis (boldface), or both.",
      "properties": [
        {
          "name": "bold",
          "type": "boolean",
          "required": true
        },
        {
          "name": "italic",
          "type": "boolean",
          "required": true
        },
        {
          "name": "kind",
          "type": "string",
          "required": true
        }
      ]
    },
    "DocExpandable": {
      "name": "DocExpandable",
      "type": "class",
      "description": "Represents an Expandable component for Mintlify documentation. Renders as: ...",
      "properties": [
        {
          "name": "content",
          "type": "DocSection",
          "required": true
        },
        {
          "name": "kind",
          "type": "string",
          "required": true
        },
        {
          "name": "title",
          "type": "string",
          "required": true
        }
      ]
    },
    "DocHeading": {
      "name": "DocHeading",
      "type": "class",
      "description": "Represents a section header similar to an HTML `<h1>` or `<h2>` element.",
      "properties": [
        {
          "name": "kind",
          "type": "string",
          "required": true
        },
        {
          "name": "level",
          "type": "number",
          "required": true
        },
        {
          "name": "title",
          "type": "string",
          "required": true
        }
      ]
    },
    "DocNoteBox": {
      "name": "DocNoteBox",
      "type": "class",
      "description": "Represents a note box, which is typically displayed as a bordered box containing informational text.",
      "properties": [
        {
          "name": "content",
          "type": "DocSection",
          "required": true
        },
        {
          "name": "kind",
          "type": "string",
          "required": true
        }
      ]
    },
    "DocTable": {
      "name": "DocTable",
      "type": "class",
      "description": "Represents table, similar to an HTML `<table>` element.",
      "properties": [
        {
          "name": "header",
          "type": "DocTableRow",
          "required": true
        },
        {
          "name": "kind",
          "type": "string",
          "required": true
        },
        {
          "name": "rows",
          "type": "ReadonlyArray<DocTableRow>",
          "required": true
        }
      ]
    },
    "DocTableCell": {
      "name": "DocTableCell",
      "type": "class",
      "description": "Represents table cell, similar to an HTML `<td>` element.",
      "properties": [
        {
          "name": "content",
          "type": "DocSection",
          "required": true
        },
        {
          "name": "kind",
          "type": "string",
          "required": true
        }
      ]
    },
    "DocTableRow": {
      "name": "DocTableRow",
      "type": "class",
      "description": "Represents table row, similar to an HTML `<tr>` element.",
      "properties": [
        {
          "name": "cells",
          "type": "ReadonlyArray<DocTableCell>",
          "required": true
        },
        {
          "name": "kind",
          "type": "string",
          "required": true
        }
      ]
    },
    "DocumentationCoverageStats": {
      "name": "DocumentationCoverageStats",
      "type": "interface",
      "description": "Overall documentation coverage statistics",
      "properties": [
        {
          "name": "coveragePercent",
          "type": "number",
          "required": true
        },
        {
          "name": "documented",
          "type": "number",
          "required": true
        },
        {
          "name": "total",
          "type": "number",
          "required": true
        },
        {
          "name": "undocumented",
          "type": "number",
          "required": true
        },
        {
          "name": "withExamples",
          "type": "number",
          "required": true
        },
        {
          "name": "withRemarks",
          "type": "number",
          "required": true
        }
      ]
    },
    "DocumentationError": {
      "name": "DocumentationError",
      "type": "class",
      "description": "Base class for all documentation generation errors.",
      "properties": [
        {
          "name": "code",
          "type": "ErrorCode",
          "description": "Standardized error code for programmatic handling",
          "required": true
        },
        {
          "name": "context",
          "type": "ErrorContext",
          "description": "Additional context about the error",
          "required": true
        },
        {
          "name": "isUserError",
          "type": "boolean",
          "description": "Whether this error represents a user error (vs system error)",
          "required": true
        },
        {
          "name": "timestamp",
          "type": "Date",
          "description": "Timestamp when the error occurred",
          "required": true
        }
      ]
    },
    "DocumentationHelper": {
      "name": "DocumentationHelper",
      "type": "class",
      "description": "Helper class for generating consistent documentation with Mintlify components"
    },
    "DocumentationStatistics": {
      "name": "DocumentationStatistics",
      "type": "interface",
      "description": "Complete documentation statistics",
      "properties": [
        {
          "name": "apiSurface",
          "type": "ApiSurfaceStats",
          "required": true
        },
        {
          "name": "coverage",
          "type": "DocumentationCoverageStats",
          "required": true
        },
        {
          "name": "generatedFiles",
          "type": "GeneratedFilesStats",
          "required": true
        },
        {
          "name": "projectName",
          "type": "string",
          "required": false
        }
      ]
    },
    "DocumentationStats": {
      "name": "DocumentationStats",
      "type": "class",
      "description": "Utility class for collecting documentation statistics"
    },
    "ErrorBoundary": {
      "name": "ErrorBoundary",
      "type": "class",
      "description": "Error boundary for handling errors during documentation generation."
    },
    "ErrorBoundaryOptions": {
      "name": "ErrorBoundaryOptions",
      "type": "interface",
      "properties": [
        {
          "name": "continueOnError",
          "type": "boolean",
          "description": "Whether to continue processing when encountering non-critical errors",
          "required": false
        },
        {
          "name": "errorLogPath",
          "type": "string",
          "description": "Path to log error details (optional)",
          "required": false
        },
        {
          "name": "includeStackTraces",
          "type": "boolean",
          "description": "Whether to include stack traces in error logs",
          "required": false
        },
        {
          "name": "logErrors",
          "type": "boolean",
          "description": "Whether to log detailed error information",
          "required": false
        },
        {
          "name": "maxErrors",
          "type": "number",
          "description": "Maximum number of errors before failing completely",
          "required": false
        }
      ]
    },
    "ErrorContext": {
      "name": "ErrorContext",
      "type": "interface",
      "properties": [
        {
          "name": "cause",
          "type": "Error",
          "description": "The original error that caused this error (for error chaining)",
          "required": false
        },
        {
          "name": "command",
          "type": "string",
          "description": "Command that was executed (for command-related errors)",
          "required": false
        },
        {
          "name": "data",
          "type": "Record<string, unknown>",
          "description": "Additional context data relevant to the error",
          "required": false
        },
        {
          "name": "exitCode",
          "type": "number",
          "description": "Exit code from a failed command",
          "required": false
        },
        {
          "name": "operation",
          "type": "string",
          "description": "The operation being performed when the error occurred",
          "required": false
        },
        {
          "name": "resource",
          "type": "string",
          "description": "The file or resource that caused the error",
          "required": false
        },
        {
          "name": "suggestion",
          "type": "string",
          "description": "Suggestion for how to fix the error",
          "required": false
        }
      ]
    },
    "ErrorResult": {
      "name": "ErrorResult",
      "type": "interface",
      "properties": [
        {
          "name": "data",
          "type": "T",
          "description": "The result data if successful",
          "required": false
        },
        {
          "name": "error",
          "type": "DocumentationError",
          "description": "The error if failed",
          "required": false
        },
        {
          "name": "recovered",
          "type": "boolean",
          "description": "Whether this was recovered from a previous error",
          "required": false
        },
        {
          "name": "success",
          "type": "boolean",
          "description": "Whether the operation succeeded",
          "required": true
        }
      ]
    },
    "FileSystemError": {
      "name": "FileSystemError",
      "type": "class",
      "description": "File system-related errors"
    },
    "GeneratedFilesStats": {
      "name": "GeneratedFilesStats",
      "type": "interface",
      "description": "Statistics about generated documentation files",
      "properties": [
        {
          "name": "averageSize",
          "type": "number",
          "required": true
        },
        {
          "name": "mdxFiles",
          "type": "number",
          "required": true
        },
        {
          "name": "totalSize",
          "type": "number",
          "required": true
        }
      ]
    },
    "GlobalErrorBoundary": {
      "name": "GlobalErrorBoundary",
      "type": "class",
      "description": "Global error boundary instance for the application."
    },
    "ICustomMarkdownEmitterOptions": {
      "name": "ICustomMarkdownEmitterOptions",
      "type": "interface",
      "description": "Configuration options for CustomMarkdownEmitter",
      "properties": [
        {
          "name": "contextApiItem",
          "type": "ApiItem | undefined",
          "required": true
        },
        {
          "name": "onGetFilenameForApiItem",
          "type": "(apiItem: ApiItem) => string | undefined",
          "required": true
        }
      ]
    },
    "IDocEmphasisSpanParameters": {
      "name": "IDocEmphasisSpanParameters",
      "type": "interface",
      "description": "Constructor parameters for .",
      "properties": [
        {
          "name": "bold",
          "type": "boolean",
          "required": false
        },
        {
          "name": "italic",
          "type": "boolean",
          "required": false
        }
      ]
    },
    "IDocHeadingParameters": {
      "name": "IDocHeadingParameters",
      "type": "interface",
      "description": "Constructor parameters for .",
      "properties": [
        {
          "name": "level",
          "type": "number",
          "required": false
        },
        {
          "name": "title",
          "type": "string",
          "required": true
        }
      ]
    },
    "IDocNoteBoxParameters": {
      "name": "IDocNoteBoxParameters",
      "type": "interface",
      "description": "Constructor parameters for ."
    },
    "IDocTableCellParameters": {
      "name": "IDocTableCellParameters",
      "type": "interface",
      "description": "Constructor parameters for ."
    },
    "IDocTableParameters": {
      "name": "IDocTableParameters",
      "type": "interface",
      "description": "Constructor parameters for .",
      "properties": [
        {
          "name": "headerCells",
          "type": "ReadonlyArray<DocTableCell>",
          "required": false
        },
        {
          "name": "headerTitles",
          "type": "string[]",
          "required": false
        }
      ]
    },
    "IDocTableRowParameters": {
      "name": "IDocTableRowParameters",
      "type": "interface",
      "description": "Constructor parameters for ."
    },
    "IMarkdownDocumenterOptions": {
      "name": "IMarkdownDocumenterOptions",
      "type": "interface",
      "description": "Configuration options for MarkdownDocumenter",
      "properties": [
        {
          "name": "apiModel",
          "type": "ApiModel",
          "required": true
        },
        {
          "name": "convertReadme",
          "type": "boolean",
          "required": false
        },
        {
          "name": "docsJsonPath",
          "type": "string",
          "required": false
        },
        {
          "name": "enableMenu",
          "type": "boolean",
          "required": false
        },
        {
          "name": "groupName",
          "type": "string",
          "required": false
        },
        {
          "name": "outputFolder",
          "type": "string",
          "required": true
        },
        {
          "name": "readmeTitle",
          "type": "string",
          "required": false
        },
        {
          "name": "tabName",
          "type": "string",
          "required": false
        },
        {
          "name": "templates",
          "type": "{ userTemplateDir?: string; overrides?: Record<string, string>; cache?: boolean; strict?: boolean; }",
          "description": "Template configuration for customizing output",
          "required": false
        }
      ]
    },
    "IMarkdownEmitterContext": {
      "name": "IMarkdownEmitterContext",
      "type": "interface",
      "description": "Context for markdown emission",
      "properties": [
        {
          "name": "boldRequested",
          "type": "boolean",
          "required": true
        },
        {
          "name": "italicRequested",
          "type": "boolean",
          "required": true
        },
        {
          "name": "options",
          "type": "TOptions",
          "required": true
        },
        {
          "name": "writer",
          "type": "IndentedWriter",
          "required": true
        },
        {
          "name": "writingBold",
          "type": "boolean",
          "required": true
        },
        {
          "name": "writingItalic",
          "type": "boolean",
          "required": true
        }
      ]
    },
    "IMarkdownEmitterOptions": {
      "name": "IMarkdownEmitterOptions",
      "type": "interface",
      "description": "Configuration options for MarkdownEmitter"
    },
    "IndentedWriter": {
      "name": "IndentedWriter",
      "type": "class",
      "description": "A utility for writing indented text.",
      "properties": [
        {
          "name": "defaultIndentPrefix",
          "type": "string",
          "description": "The text characters used to create one level of indentation. Two spaces by default.",
          "required": true
        }
      ]
    },
    "IReturnData": {
      "name": "IReturnData",
      "type": "interface",
      "properties": [
        {
          "name": "description",
          "type": "string",
          "required": false
        },
        {
          "name": "type",
          "type": "string",
          "required": true
        },
        {
          "name": "typePath",
          "type": "string",
          "required": false
        }
      ]
    },
    "ITableData": {
      "name": "ITableData",
      "type": "interface",
      "properties": [
        {
          "name": "headers",
          "type": "string[]",
          "required": true
        },
        {
          "name": "rows",
          "type": "ITableRow[]",
          "required": true
        },
        {
          "name": "title",
          "type": "string",
          "required": true
        }
      ]
    },
    "ITableRow": {
      "name": "ITableRow",
      "type": "interface",
      "properties": [
        {
          "name": "defaultValue",
          "type": "string",
          "required": false
        },
        {
          "name": "description",
          "type": "string",
          "required": false
        },
        {
          "name": "isDeprecated",
          "type": "boolean",
          "required": false
        },
        {
          "name": "isInherited",
          "type": "boolean",
          "required": false
        },
        {
          "name": "isOptional",
          "type": "boolean",
          "required": false
        },
        {
          "name": "modifiers",
          "type": "string[]",
          "required": false
        },
        {
          "name": "title",
          "type": "string",
          "required": true
        },
        {
          "name": "titlePath",
          "type": "string",
          "required": false
        },
        {
          "name": "type",
          "type": "string",
          "required": false
        },
        {
          "name": "typePath",
          "type": "string",
          "required": false
        }
      ]
    },
    "ITemplateData": {
      "name": "ITemplateData",
      "type": "interface",
      "description": "Interface for template data that gets passed to EJS templates",
      "properties": [
        {
          "name": "abstractClasses",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "apiItem",
          "type": "{ name: string; kind: string; displayName: string; description?: string; summary?: string; remarks?: string; signature?: string; isDeprecated?: boolean; isAlpha?: boolean; isBeta?: boolean; releaseTag?: string; }",
          "required": true
        },
        {
          "name": "classes",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "constructors",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "enumerations",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "events",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "examples",
          "type": "string[]",
          "required": false
        },
        {
          "name": "functions",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "heritageTypes",
          "type": "Array<{ name: string; path?: string; }>",
          "required": false
        },
        {
          "name": "interfaces",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "members",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "methods",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "namespaces",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "navigation",
          "type": "{ id: string; title: string; group?: string; }",
          "required": false
        },
        {
          "name": "page",
          "type": "{ title: string; description: string; icon: string; breadcrumb: Array<{ name: string; path?: string; }>; }",
          "required": true
        },
        {
          "name": "parameters",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "properties",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "returnType",
          "type": "IReturnData",
          "required": false
        },
        {
          "name": "typeAliases",
          "type": "ITableRow[]",
          "required": false
        },
        {
          "name": "variables",
          "type": "ITableRow[]",
          "required": false
        }
      ]
    },
    "ITemplateEngineOptions": {
      "name": "ITemplateEngineOptions",
      "type": "interface",
      "description": "Configuration for template engine",
      "properties": [
        {
          "name": "cache",
          "type": "boolean",
          "required": false
        },
        {
          "name": "strict",
          "type": "boolean",
          "required": false
        },
        {
          "name": "templateDir",
          "type": "string",
          "required": false
        }
      ]
    },
    "ITemplateManagerOptions": {
      "name": "ITemplateManagerOptions",
      "type": "interface",
      "description": "Configuration for template manager",
      "properties": [
        {
          "name": "defaultTemplateDir",
          "type": "string",
          "required": false
        },
        {
          "name": "overrides",
          "type": "Record<string, string>",
          "description": "Individual template overrides - map template names to file paths",
          "required": false
        },
        {
          "name": "userTemplateDir",
          "type": "string",
          "required": false
        }
      ]
    },
    "LiquidTemplateEngine": {
      "name": "LiquidTemplateEngine",
      "type": "class",
      "description": "LiquidJS-based template engine implementation",
      "properties": [
        {
          "name": "liquid",
          "type": "Liquid",
          "description": "Get the Liquid engine for direct access",
          "required": true
        },
        {
          "name": "templateDir",
          "type": "string",
          "description": "Get the template directory (public for template manager)",
          "required": true
        }
      ]
    },
    "LiquidTemplateManager": {
      "name": "LiquidTemplateManager",
      "type": "class",
      "description": "Template manager that uses LiquidJS with template merging",
      "properties": [
        {
          "name": "liquidEngine",
          "type": "LiquidTemplateEngine",
          "description": "Get the Liquid engine for direct access",
          "required": true
        },
        {
          "name": "mergedTemplateDir",
          "type": "string | undefined",
          "description": "Get the current merged template directory (for debugging)",
          "required": true
        },
        {
          "name": "templateDataConverter",
          "type": "TemplateDataConverter",
          "description": "Get template data converter",
          "required": true
        }
      ]
    },
    "MarkdownDocumenter": {
      "name": "MarkdownDocumenter",
      "type": "class",
      "description": "Core class for rendering API documentation in Mintlify-compatible MDX format.This class takes TypeScript API model data and converts it into MDX files with proper Mintlify frontmatter, navigation integration, and formatting suitable for documentation sites."
    },
    "MarkdownEmitter": {
      "name": "MarkdownEmitter",
      "type": "class",
      "description": "Renders MarkupElement content in the Markdown file format. For more info: https://en.wikipedia.org/wiki/Markdown"
    },
    "MessageReportingItem": {
      "name": "MessageReportingItem",
      "type": "interface",
      "properties": [
        {
          "name": "addToApiReportFile",
          "type": "boolean",
          "required": false
        },
        {
          "name": "logLevel",
          "type": "'error' | 'warning' | 'none'",
          "required": false
        }
      ]
    },
    "MintlifyTsDocsConfig": {
      "name": "MintlifyTsDocsConfig",
      "type": "interface",
      "properties": [
        {
          "name": "$schema",
          "type": "string",
          "description": "JSON Schema reference",
          "required": false
        },
        {
          "name": "apiExtractor",
          "type": "ApiExtractorConfig",
          "description": "API Extractor configuration (written to .tsdocs/api-extractor.json)",
          "required": false
        },
        {
          "name": "convertReadme",
          "type": "boolean",
          "description": "Whether to convert README.md to index.mdx",
          "required": false
        },
        {
          "name": "docsJson",
          "type": "string",
          "description": "Path to Mintlify's docs.json file for navigation integration. If not specified, will search for docs.json in common locations.",
          "required": false
        },
        {
          "name": "entryPoint",
          "type": "string",
          "description": "Path to the main TypeScript declaration file (.d.ts) to document. If not specified, will auto-detect from package.json or common paths.",
          "required": false
        },
        {
          "name": "groupName",
          "type": "string",
          "description": "Name of the group within the tab for organizing API documentation pages. Defaults to 'API'",
          "required": false
        },
        {
          "name": "outputFolder",
          "type": "string",
          "description": "Directory where MDX documentation files will be generated. Defaults to './docs/reference'",
          "required": false
        },
        {
          "name": "readmeTitle",
          "type": "string",
          "description": "Title for the converted README file",
          "required": false
        },
        {
          "name": "tabName",
          "type": "string",
          "description": "Name of the tab in Mintlify navigation where API docs will appear. Defaults to 'API Reference'",
          "required": false
        },
        {
          "name": "templates",
          "type": "TemplateConfig",
          "description": "Template customization options",
          "required": false
        }
      ]
    },
    "NavigationItem": {
      "name": "NavigationItem",
      "type": "interface",
      "description": "Navigation item interface for Mintlify docs.json structure",
      "properties": [
        {
          "name": "apiKind",
          "type": "ApiItemKind",
          "required": false
        },
        {
          "name": "displayName",
          "type": "string",
          "required": false
        },
        {
          "name": "group",
          "type": "string",
          "required": false
        },
        {
          "name": "icon",
          "type": "string",
          "required": false
        },
        {
          "name": "page",
          "type": "string",
          "required": false
        },
        {
          "name": "pages",
          "type": "Array<string | NavigationItem>",
          "required": false
        },
        {
          "name": "parentPage",
          "type": "string",
          "required": false
        }
      ]
    },
    "NavigationManager": {
      "name": "NavigationManager",
      "type": "class",
      "description": "Manages Mintlify navigation structure including docs.json updates and hierarchical organization"
    },
    "NavigationManagerOptions": {
      "name": "NavigationManagerOptions",
      "type": "interface",
      "description": "Configuration options for navigation manager",
      "properties": [
        {
          "name": "docsJsonPath",
          "type": "string",
          "description": "Path to the docs.json file",
          "required": false
        },
        {
          "name": "enableMenu",
          "type": "boolean",
          "description": "Enable menu for the group in navigation",
          "required": false
        },
        {
          "name": "groupName",
          "type": "string",
          "description": "Group name within the tab",
          "required": false
        },
        {
          "name": "outputFolder",
          "type": "string",
          "description": "Output folder path for path calculations",
          "required": false
        },
        {
          "name": "tabName",
          "type": "string",
          "description": "Tab name in Mintlify navigation (default: \"Code Reference\")",
          "required": false
        }
      ]
    },
    "ObjectTypeAnalyzer": {
      "name": "ObjectTypeAnalyzer",
      "type": "class",
      "description": "Analyzes TypeScript type strings to extract nested object properties"
    },
    "ResolvedConfig": {
      "name": "ResolvedConfig",
      "type": "interface",
      "properties": [
        {
          "name": "apiExtractor",
          "type": "ApiExtractorConfig",
          "required": true
        },
        {
          "name": "convertReadme",
          "type": "boolean",
          "required": true
        },
        {
          "name": "docsJson",
          "type": "string",
          "required": false
        },
        {
          "name": "entryPoint",
          "type": "string",
          "required": true
        },
        {
          "name": "groupName",
          "type": "string",
          "required": true
        },
        {
          "name": "outputFolder",
          "type": "string",
          "required": true
        },
        {
          "name": "readmeTitle",
          "type": "string",
          "required": true
        },
        {
          "name": "tabName",
          "type": "string",
          "required": true
        },
        {
          "name": "templates",
          "type": "{ userTemplateDir?: string; cache: boolean; strict: boolean; }",
          "required": true
        }
      ]
    },
    "SecurityError": {
      "name": "SecurityError",
      "type": "class",
      "description": "Security-related errors"
    },
    "SecurityUtils": {
      "name": "SecurityUtils",
      "type": "class",
      "description": "Security utilities for input validation, sanitization, and secure file operations."
    },
    "TemplateConfig": {
      "name": "TemplateConfig",
      "type": "interface",
      "properties": [
        {
          "name": "cache",
          "type": "boolean",
          "description": "Whether to enable template caching",
          "required": false
        },
        {
          "name": "strict",
          "type": "boolean",
          "description": "Whether to use strict mode for templates",
          "required": false
        },
        {
          "name": "userTemplateDir",
          "type": "string",
          "description": "Directory containing custom template overrides",
          "required": false
        }
      ]
    },
    "TemplateDataConverter": {
      "name": "TemplateDataConverter",
      "type": "class",
      "description": "Converts API model data to template-friendly format"
    },
    "TemplateEngine": {
      "name": "TemplateEngine",
      "type": "class",
      "description": "Template engine that processes EJS templates with API data"
    },
    "TemplateManager": {
      "name": "TemplateManager",
      "type": "class",
      "description": "Manages template resolution and rendering with user override support"
    },
    "TypeAnalysisCache": {
      "name": "TypeAnalysisCache",
      "type": "class",
      "description": "Simple LRU cache for type analysis results"
    },
    "TypeAnalysisCacheOptions": {
      "name": "TypeAnalysisCacheOptions",
      "type": "interface",
      "description": "Configuration options for type analysis cache",
      "properties": [
        {
          "name": "enabled",
          "type": "boolean",
          "description": "Whether to enable caching",
          "required": false
        },
        {
          "name": "maxSize",
          "type": "number",
          "description": "Maximum number of cached type analyses",
          "required": false
        }
      ]
    },
    "TypeCoverageStats": {
      "name": "TypeCoverageStats",
      "type": "interface",
      "description": "Coverage statistics for a single API item type",
      "properties": [
        {
          "name": "coveragePercent",
          "type": "number",
          "required": true
        },
        {
          "name": "documented",
          "type": "number",
          "required": true
        },
        {
          "name": "total",
          "type": "number",
          "required": true
        },
        {
          "name": "undocumented",
          "type": "number",
          "required": true
        }
      ]
    },
    "TypeInfoGenerator": {
      "name": "TypeInfoGenerator",
      "type": "class",
      "description": "Generates TypeInfo.jsx file with type information for documentation"
    },
    "TypeTreeGroupProps": {
      "name": "TypeTreeGroupProps",
      "type": "interface",
      "description": "Props for the TypeTreeGroup component. Used to organize multiple related types under a common title.",
      "properties": [
        {
          "name": "children",
          "type": "React.ReactNode",
          "description": "The TypeTree components to group together",
          "required": false
        },
        {
          "name": "title",
          "type": "string",
          "description": "The title displayed above the grouped types",
          "required": true
        }
      ]
    },
    "TypeTreeProperty": {
      "name": "TypeTreeProperty",
      "type": "interface",
      "description": "Represents a single property in a TypeTree structure. This interface supports recursive nesting through the `properties` field.",
      "properties": [
        {
          "name": "defaultValue",
          "type": "string",
          "description": "The default value for this property, if any. Displayed below the description",
          "required": false
        },
        {
          "name": "deprecated",
          "type": "boolean",
          "description": "Whether this property is deprecated. Displays an orange \"deprecated\" badge when `true`",
          "required": false,
          "defaultValue": "[object Object]"
        },
        {
          "name": "description",
          "type": "string",
          "description": "Human-readable description of what this property represents",
          "required": false
        },
        {
          "name": "name",
          "type": "string",
          "description": "The name of the property or type being documented",
          "required": true
        },
        {
          "name": "properties",
          "type": "TypeTreeProperty[]",
          "description": "Array of nested properties for complex types. Each item should follow the same TypeTreeProperty structure, enabling recursive nesting.",
          "required": false
        },
        {
          "name": "required",
          "type": "boolean",
          "description": "Whether this property is required. Displays a red \"required\" badge when `true`",
          "required": false,
          "defaultValue": "[object Object]"
        },
        {
          "name": "type",
          "type": "string",
          "description": "The TypeScript type annotation (e.g., `string`, `number`, `object`, `Array<string>`)",
          "required": true
        }
      ]
    },
    "TypeTreeProps": {
      "name": "TypeTreeProps",
      "type": "type",
      "description": "Props for the TypeTree component. Extends TypeTreeProperty to include all properties plus component-specific props."
    },
    "Utilities": {
      "name": "Utilities",
      "type": "class"
    },
    "ValidationError": {
      "name": "ValidationError",
      "type": "class",
      "description": "Validation errors for user input"
    }
  }
};
